/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.View.HangHoa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import pk.SQL.connectDbSql;
import pk.doiTuong.hanghoa;
import pk.view.HangHoa.showhanghoa;
import static pk.view.HangHoa.showhanghoa.sua;
import static pk.view.HangHoa.showhanghoa.them;
import static pk.view.HangHoa.showhanghoa.idMon;

/**
 *
 * @author Nguyễn Tấn Năm
 */
public class themsuahang extends javax.swing.JDialog {

    /**
     * Creates new form themsuahang
     */
    
    connectDbSql con = new connectDbSql();
    public themsuahang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ArrayList<String> list = con.Loatcombobox();
        for (String item : list) {
            comboboxloai.addItem(item.toString());
        }
    }
    Integer idMON;
    public themsuahang(java.awt.Frame parent, boolean modal, Integer idMon) {
        super(parent, modal);
        initComponents();
        t.setText("CHỈNH SỬA THÔNG TIN");
        System.out.println(t);
        idMON = idMon;
        ArrayList<hanghoa> Sua  = con.getByhanghoa(idMon);
        txtName.setText(Sua.get(0).getTenMon());
        Double a = Sua.get(0).getDonGia();
        txtdongia.setText(String.valueOf(a));
        ArrayList<String> list = con.Loatcombobox();
        for (String item : list) {
            comboboxloai.addItem(item.toString());
        }
        //comboboxloai.setSelectedItem(Sua.get(0).getTenLoai());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboboxloai = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtdongia = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        t.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        t.setText("THÊM MÓN");

        jLabel2.setText("Tên Món:");

        jLabel3.setText("Đơn giá:");

        jLabel4.setText("Loại:");

        comboboxloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxloaiActionPerformed(evt);
            }
        });

        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(comboboxloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtdongia, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(t)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdongia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboboxloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if("".equals(txtName.getText()) || "".equals(txtdongia.getText()) 
                || "".equals(comboboxloai.getSelectedItem())){
            JOptionPane.showMessageDialog(null, "ĐÃ NHẬP THIẾU DỮ LIỆU");
            System.out.println("XAC NHAN"+them);
        }
        else if (them == 2) {
            System.out.println("Da vao dia them "+con.ktloai((String) comboboxloai.getSelectedItem()));
            hanghoa hh = new hanghoa();
            hh.setTenMon(txtName.getText());
            hh.setDonGia(Double.parseDouble(txtdongia.getText()));
            hh.setIdLoai(con.ktloai((String) comboboxloai.getSelectedItem()));
            int is = con.themMon(hh);
                if(is != 0){
                    showhanghoa.a.showTable();
                  showhanghoa.a.updateUI();
                  this.setVisible(false);
                }
        }else if (sua == 3) {
            hanghoa h = new hanghoa();
            h.setTenMon(txtName.getText());
            h.setDonGia(Double.parseDouble(txtdongia.getText()));
            h.setIdLoai(con.ktloai((String) comboboxloai.getSelectedItem()));
            
            int is = con.suaMon(h,idMon);
                if(is != 0){
                  showhanghoa.a.showTable();
                  showhanghoa.a.updateUI();
                  this.setVisible(false);
                }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboboxloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxloaiActionPerformed
        
        
    }//GEN-LAST:event_comboboxloaiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxloai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel t;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtdongia;
    // End of variables declaration//GEN-END:variables
}
