/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.View.BanHang;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pk.SQL.connectDbSql;
import pk.doiTuong.ban;

/**
 *
 * @author VanThien
 */
public class setChuyenBanJPN extends javax.swing.JPanel{

    /**
     * Creates new form setChuyenBanJPN
     */
    connectDbSql conn = new connectDbSql();
    public setChuyenBanJPN() {
        initComponents();
        this.setSize(850, 511);
        Defaul();
    }
     DefaultTableModel modelMov = new DefaultTableModel();
     DefaultTableModel modelUse = new DefaultTableModel();
    public void Defaul()
    {
       modelMov.setColumnCount(0);
        modelMov.addColumn("Mã Bàn");
        modelMov.addColumn("Tên Bàn");
        modelMov.addColumn("Trạng Thái");
        
        modelUse.setColumnCount(0);
       modelUse.addColumn("Mã Bàn");
        modelUse.addColumn("Tên Bàn");
       modelUse.addColumn("Trạng Thái");
        setTablemov();
        setTableuse();
    }
  
    public void setTablemov()
    {
        modelMov.setRowCount(0);
        ArrayList<ban> arrTable = conn.getBanbyTrangThai("Trống");
        if (arrTable != null) {
            for (ban l : arrTable) {
                modelMov.addRow(new Object[]{String.valueOf(l.getIdBan()), l.getTenBan(),l.getTrangThai()});
            }
        } else {
            JOptionPane.showMessageDialog(null, "Không có bàn nào");
    }
        jtbBanMov.setModel(modelMov);
    }
    
    public void setTableuse()
    {
        modelUse.setRowCount(0);
        ArrayList<ban> arrTable = conn.getBanbyTrangThai("Đã có");
        if (arrTable != null) {
            for (ban l : arrTable) {
               modelUse.addRow(new Object[]{String.valueOf(l.getIdBan()), l.getTenBan(),l.getTrangThai()});
            }
        } else {
            JOptionPane.showMessageDialog(null, "Không có bàn nào");
    }
        jtbBanUse.setModel(modelUse);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnChonBan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbBanUse = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jpnChonBan1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbBanMov = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jpnChonBan.setBackground(new java.awt.Color(255, 255, 255));
        jpnChonBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtbBanUse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbBanUse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBanUseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbBanUse);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Chọn bàn đang dùng :  ");

        javax.swing.GroupLayout jpnChonBanLayout = new javax.swing.GroupLayout(jpnChonBan);
        jpnChonBan.setLayout(jpnChonBanLayout);
        jpnChonBanLayout.setHorizontalGroup(
            jpnChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChonBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnChonBanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnChonBanLayout.setVerticalGroup(
            jpnChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChonBanLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnChonBan1.setBackground(new java.awt.Color(255, 255, 255));
        jpnChonBan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtbBanMov.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbBanMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBanMovMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbBanMov);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Chọn bàn Chuyển đến :  ");

        javax.swing.GroupLayout jpnChonBan1Layout = new javax.swing.GroupLayout(jpnChonBan1);
        jpnChonBan1.setLayout(jpnChonBan1Layout);
        jpnChonBan1Layout.setHorizontalGroup(
            jpnChonBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChonBan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChonBan1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnChonBan1Layout.setVerticalGroup(
            jpnChonBan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChonBan1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Chuyển");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jpnChonBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jpnChonBan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpnChonBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnChonBan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    String maHD;
    int banUse =-1;
    int banMov=-1;
    private void jtbBanUseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBanUseMouseClicked
        int i = jtbBanUse.getSelectedRow();
        int ban = Integer.valueOf( jtbBanUse.getValueAt(i, 0).toString().trim());
        maHD = conn.FindHoaDonByban(String.valueOf(ban));
        banUse = ban;
    }//GEN-LAST:event_jtbBanUseMouseClicked

    private void jtbBanMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBanMovMouseClicked
        // TODO add your handling code here:
        int i = jtbBanMov.getSelectedRow();
        int ban = Integer.valueOf( jtbBanMov.getValueAt(i, 0).toString().trim());
        banMov = ban;
    }//GEN-LAST:event_jtbBanMovMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(banMov <0 || banUse <0 )
        {
            JOptionPane.showMessageDialog(jpnChonBan,"Vui Lòng chọn đủ hai bàn !");
        }
        else
        {
        conn.UpdChuyenBan(maHD,banMov);
        conn.updateTrangThaiban(String.valueOf(banUse),"Trống");
        conn.updateTrangThaiban(String.valueOf(banMov),"Đã có");
        Defaul();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnChonBan;
    private javax.swing.JPanel jpnChonBan1;
    private javax.swing.JTable jtbBanMov;
    private javax.swing.JTable jtbBanUse;
    // End of variables declaration//GEN-END:variables
}
