/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.View.BanHang;


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pk.SQL.connectDbSql;
import pk.doiTuong.ChitietHoaDon;

import pk.doiTuong.ban;



/**
 *
 * @author VanThien
 */
public class setThanhToanJPN extends setGoiMonJPN{

    /**
     * Creates new form setThanhToanJPN
     */
    connectDbSql conn = new connectDbSql();
    DefaultTableModel tbmodel = new DefaultTableModel();
    public setThanhToanJPN() {
        initComponents();
        this.setSize(850, 511);
        setDefaul();
        setTableBan();
       
    }
        public void setDefaul()
        {
        jpnhoaDon.setVisible(false);
      
        tbmodel.setColumnCount(0);
        tbmodel.setRowCount(0);
        tbmodel.addColumn("MÃ BÀN");
        tbmodel.addColumn("TÊN BÀN");
        }
  
    @Override
    public void setListMontheoBan(String idHD)
    {
        super.setListMontheoBan(idHD);
        jtbMon.setModel(model);
        
    }
    String idBan;
    public static ChitietHoaDon cthd ;
    public void setTableBan()
    {
        tbmodel.setRowCount(0);
        ArrayList<ban> arrTable = conn.getBanbyTrangThai("Đã có");
        if (arrTable != null) {
            for (ban l : arrTable) {
                tbmodel.addRow(new Object[]{String.valueOf(l.getIdBan()), l.getTenBan()});
            }
        } else {
            JOptionPane.showMessageDialog(null, "Không có bàn nào");
    }
        jtableBanThanhToan.setModel(tbmodel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        btnTinhTienThua = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlbTongTien = new javax.swing.JLabel();
        txtTienKhacch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jlbTienThua = new javax.swing.JLabel();
        btnXuatHoaDon = new javax.swing.JButton();
        jpnChonBan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableBanThanhToan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jpnhoaDon = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jlbBan = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbMon = new javax.swing.JTable();
        btnXacNhanMon = new javax.swing.JButton();
        jbtXuatHoaDon = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbkhuyenMai = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jlbTienbanDau = new javax.swing.JLabel();
        jlbTiensaukhuyeMai = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jblMaHoaDon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jDialog1.setLocation(new java.awt.Point(700, 200));
        jDialog1.setMinimumSize(new java.awt.Dimension(400, 300));

        btnTinhTienThua.setText("Tính");
        btnTinhTienThua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienThuaActionPerformed(evt);
            }
        });

        jLabel10.setText("Tổng Tiền : ");

        jLabel11.setText("Nhập Tiền Khách Trả : ");

        jlbTongTien.setText("jLabel12");

        jLabel13.setText("Tiền Thừa : ");

        jlbTienThua.setText("jLabel14");

        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTienKhacch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXuatHoaDon))
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnTinhTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119))
                            .addGroup(jDialog1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbTienThua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(145, 145, 145))))))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlbTongTien))
                .addGap(23, 23, 23)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTienKhacch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jlbTienThua))
                .addGap(26, 26, 26)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhTienThua)
                    .addComponent(btnXuatHoaDon))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jpnChonBan.setBackground(new java.awt.Color(255, 255, 255));
        jpnChonBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtableBanThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtableBanThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableBanThanhToanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableBanThanhToan);

        jLabel1.setText("Chọn bàn thanh toán : ");

        javax.swing.GroupLayout jpnChonBanLayout = new javax.swing.GroupLayout(jpnChonBan);
        jpnChonBan.setLayout(jpnChonBanLayout);
        jpnChonBanLayout.setHorizontalGroup(
            jpnChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChonBanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnChonBanLayout.setVerticalGroup(
            jpnChonBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChonBanLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnhoaDon.setBackground(new java.awt.Color(255, 255, 255));
        jpnhoaDon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Bàn Số :  ");

        jlbBan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlbBan.setText("jLabel6");

        jtbMon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Món", "Số lượng", ""
            }
        ));
        jScrollPane3.setViewportView(jtbMon);

        btnXacNhanMon.setText("Tính Tiền Thừa");
        btnXacNhanMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanMonActionPerformed(evt);
            }
        });

        jbtXuatHoaDon.setText("Xuất Hóa đơn");
        jbtXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtXuatHoaDonActionPerformed(evt);
            }
        });

        jLabel8.setText("Món đã gọi : ");

        jLabel2.setText("Giảm giá : ");

        jLabel3.setText("Tổng Tiền : ");

        cbkhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "20", "30", "40", "50" }));
        cbkhuyenMai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbkhuyenMaiItemStateChanged(evt);
            }
        });

        jLabel4.setText("Tiền chưa giảm giá : ");

        jlbTienbanDau.setText("jLabel7");

        jlbTiensaukhuyeMai.setText("jLabel7");

        jLabel7.setText("%");

        jLabel9.setText("Mã Hóa Đơn : ");

        jblMaHoaDon.setText("jLabel10");

        javax.swing.GroupLayout jpnhoaDonLayout = new javax.swing.GroupLayout(jpnhoaDon);
        jpnhoaDon.setLayout(jpnhoaDonLayout);
        jpnhoaDonLayout.setHorizontalGroup(
            jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnhoaDonLayout.createSequentialGroup()
                        .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jpnhoaDonLayout.createSequentialGroup()
                                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addGroup(jpnhoaDonLayout.createSequentialGroup()
                                        .addGap(118, 118, 118)
                                        .addComponent(jLabel5)
                                        .addGap(20, 20, 20)
                                        .addComponent(jlbBan))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpnhoaDonLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlbTienbanDau, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnhoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(cbkhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(185, 185, 185))
                    .addGroup(jpnhoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55)
                        .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jblMaHoaDon)
                            .addComponent(jlbTiensaukhuyeMai, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jpnhoaDonLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnXacNhanMon)
                .addGap(52, 52, 52)
                .addComponent(jbtXuatHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnhoaDonLayout.setVerticalGroup(
            jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnhoaDonLayout.createSequentialGroup()
                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbBan)
                    .addComponent(jLabel5))
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlbTienbanDau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbkhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbTiensaukhuyeMai))
                .addGap(18, 18, 18)
                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jblMaHoaDon))
                .addGap(42, 42, 42)
                .addGroup(jpnhoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhanMon)
                    .addComponent(jbtXuatHoaDon))
                .addGap(145, 145, 145))
        );

        jButton1.setText("Làm Mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnChonBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jpnhoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpnChonBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jpnhoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanMonActionPerformed
        
        jlbTongTien.setText(jlbTiensaukhuyeMai.getText());
        txtTienKhacch.setText("0");
        jDialog1.setVisible(true);
        
    }//GEN-LAST:event_btnXacNhanMonActionPerformed

    private void jbtXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtXuatHoaDonActionPerformed

       JOptionPane.showMessageDialog(jpnChonBan, "Thanh toán hoàn tất !");
       con.updateTrangThaiban(idBan,"Trống");
       setTableBan();  
       conn.UpdateChiTietHoaDon(cthd);
       conn.UpdatetienHoaDon(maHD,jlbTiensaukhuyeMai.getText());
       jpnhoaDon.setVisible(false);
    }//GEN-LAST:event_jbtXuatHoaDonActionPerformed
    
    private void jtableBanThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableBanThanhToanMouseClicked
        cthd  = new ChitietHoaDon();
        String maHD;
        int i = jtableBanThanhToan.getSelectedRow();
        int ban = Integer.valueOf( jtableBanThanhToan.getValueAt(i, 0).toString().trim());
        idBan = String.valueOf(ban);
        jlbBan.setText(String.valueOf(ban));
            int confirm = JOptionPane.showConfirmDialog(this, "Thanh toán cho bàn này ?");
            if (confirm == JOptionPane.YES_OPTION) {
                jpnhoaDon.setVisible(true);
                maHD = conn.FindHoaDonByban(String.valueOf(ban));
                System.out.println("ma hoa don tim dc la : " + maHD);
                setListMontheoBan(maHD);
                
                Double tienBanDau = 0.0;
                int soluong = 0;
                for(int k = 0; k<jtbMon.getRowCount();k++)
                {
                    tienBanDau = tienBanDau +Double.valueOf(jtbMon.getModel().getValueAt(k,2).toString());
                    soluong = Integer.valueOf(jtbMon.getModel().getValueAt(k,1).toString());
                }
                jblMaHoaDon.setText(maHD);
                jlbTienbanDau.setText(String.valueOf(tienBanDau));
                Double khuyenMai = Double.valueOf(cbkhuyenMai.getSelectedItem().toString());
                Double tienSauGiam = tienBanDau*(1-khuyenMai/100);
                jlbTiensaukhuyeMai.setText( String.valueOf(tienSauGiam));
                
                ///Lấy dũ liệu hóa đơn 
                cthd.setMaHD(maHD);
                cthd.setIdMon(maMon);
                cthd.setSoLuong(soluong);
            }
            
            
        
            
        
    }//GEN-LAST:event_jtableBanThanhToanMouseClicked

    private void cbkhuyenMaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbkhuyenMaiItemStateChanged
        // TODO add your handling code here:
        Double tienBanDau = Double.valueOf(jlbTienbanDau.getText());
        Double khuyenMai = Double.valueOf(cbkhuyenMai.getSelectedItem().toString());
        Double tienSauGiam = tienBanDau*(1-khuyenMai/100);
        
       jlbTiensaukhuyeMai.setText( String.valueOf(tienSauGiam));
       ///Tiếp tực lấy dữ liệu CTHD
          cthd.setMaGiamGia(khuyenMai);
          
    }//GEN-LAST:event_cbkhuyenMaiItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setTableBan();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        // TODO add your handling code here:
        jbtXuatHoaDon.doClick();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void btnTinhTienThuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienThuaActionPerformed
        // TODO add your handling code here:
         jlbTongTien.setText(jlbTiensaukhuyeMai.getText());
        jlbTienThua.setText(String.valueOf(Double.valueOf(txtTienKhacch.getText())-Double.valueOf(jlbTiensaukhuyeMai.getText())));
       
    }//GEN-LAST:event_btnTinhTienThuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinhTienThua;
    private javax.swing.JButton btnXacNhanMon;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JComboBox<String> cbkhuyenMai;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jblMaHoaDon;
    private javax.swing.JButton jbtXuatHoaDon;
    private javax.swing.JLabel jlbBan;
    private javax.swing.JLabel jlbTienThua;
    private javax.swing.JLabel jlbTienbanDau;
    private javax.swing.JLabel jlbTiensaukhuyeMai;
    private javax.swing.JLabel jlbTongTien;
    private javax.swing.JPanel jpnChonBan;
    private javax.swing.JPanel jpnhoaDon;
    private javax.swing.JTable jtableBanThanhToan;
    private javax.swing.JTable jtbMon;
    private javax.swing.JTextField txtTienKhacch;
    // End of variables declaration//GEN-END:variables
}
